config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages/landing_pages#index'

  devise_for :users,
             path: 'users',
             controllers: {
               sessions: 'users/sessions', passwords: 'users/passwords'
             }

  devise_scope :user do
    get '/signin', to: 'users/sessions#new'
    get '/signup', to: 'users/registrations#new'
  end

  get '/termsofservice', to: 'static_pages/tos_pages#index'
  get '/privacypolicy', to: 'static_pages/privacy_policy_pages#index'

  namespace :users do
    resource :registrations, only: %i[create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/accessible.rb
# frozen_string_literal: true

module Accessible
  extend ActiveSupport::Concern
  included do
    before_action :check_user
  end

    protected

  def check_user
    if current_user
      flash.clear
      # The authenticated root path can be defined in your routes.rb in: devise_scope :user do...
      # current_user.update_attribute(:active, true)
      redirect_to users_dashboards_homes_path
    # elsif current_worker
    #   flash.clear
    #   # if you have rails_admin. You can redirect anywhere really
    #   redirect_to workers_dashboards_open_appointments_path
    # elsif current_executive
    #   flash.clear
    #   # if you have rails_admin. You can redirect anywhere really
    #   redirect_to executives_dashboards_homes_path
   end
  end
end

app/controllers/static_pages/landing_pages_controller.rb
# frozen_string_literal: true
class StaticPages::LandingPagesController < ApplicationController
  def index
  end
end

app/controllers/static_pages/privacy_policy_pages_controller.rb
# frozen_string_literal: true
class StaticPages::PrivacyPolicyPagesController < ApplicationController

  # privacypolicy_path
  def index

  end

end

app/controllers/static_pages/tos_pages_controller.rb
# frozen_string_literal: true
class StaticPages::TosPagesController < ApplicationController

  # termsofservice_path
  def index

  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  def after_resetting_password_path_for(resource)
    # super(resource)
    new_user_session_path
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    flash[:notice] = "We have sent an email with the instructions to reset your password"
    super(resource_name)
    new_user_password_path
    
    # redirect_to new_user_password_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < ApplicationController
  def new; end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save!
      # @user.send_welcome_email!

      sign_in @user

      redirect_to root_path,flash: {
        notice: 'user created'
      }
    else
      redirect_to signup_path, flash: {
        error: @user.errors.full_messages[0]
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(%i[
     email
     password
     password_confirmation
    ])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  include Accessible
  skip_before_action :check_user, except: %i[new create]
  # # GET /resource/sign_in
  # def new
  #   super
  # end

  # # POST /resource/sign_in
  # def create
  #   super
  #   flash.delete(:notice)
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    super(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    super(resource)
    signin_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   added_attrs = %i(full_name phone email)
  #   devise_parameter_sanitizer.permit(:sign_in, keys: added_attrs)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Rails Starter Pack</title>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= render 'layouts/headers/default' %>

    <%= render 'layouts/headers/seo_meta_tags' %>

    <%= render 'layouts/headers/font_import_links' %>
    <%= render 'layouts/headers/ionicons' %>
    <%= render 'layouts/headers/google_recaptcha'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/headers/google_tag_manager'%>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>


  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/banners/_top_banner.html.erb
<div class="w-full px-4 py-2 flex justify-center items-center bg-primary-purple">
  <h3 class="text-white font-semibold text-center">
    This is a cool banner to announce something cool! 
    <%= link_to 'Click Here!', root_path, class: 'underline font-semibold text-white'%>
  </h3>
</div>

app/views/layouts/headers/_default.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

app/views/layouts/headers/_font_import_links.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">

app/views/layouts/headers/_google_recaptcha.html.erb
<!-- 
<script src="https://www.google.com/recaptcha/api.js?onload=onLoadCallback&render=explicit" async defer></script>
-->

app/views/layouts/headers/_google_tag_manager.html.erb
<% if Rails.env.production?%>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<INSERT_TARGET_ID_HERE>">
  </script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<INSERT_TARGET_ID_HERE>');
  </script>
<% end %>

app/views/layouts/headers/_ionicons.html.erb
<script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule="" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>

app/views/layouts/headers/_seo_meta_tags.html.erb
<meta property="image" content="<%=image_url("preview-card.png")%>" />
<meta property="title" content="Add something here...">
<meta property="type" content="website">
<meta property="site_name" content="Add something here...">
<meta property="url" content="https://www.example.com">
<meta property="description" content="Add something here...">

<meta property="og:image" content="<%=image_url("preview-card.png")%>" />
<meta property="og:title" content="Add something here...">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Add something here...">
<meta property="og:url" content="Add something here...">
<meta property="og:description" content="Add something here...">

<meta name="msvalidate.01" content="add_code_here" />

app/views/static_pages/landing_pages/_social_card.html.erb
<%# social review card item START%>
<div class="max-w-xs mb-10 md:mb-0 md:mr-6">
  <div class="w-full flex justify-between items-center">
    <div class="w-1/3 flex justify-start items-center">
      <%= image_tag 'person-circle-outline.png', class: ''%> 
    </div> 

    <div class="w-2/3 flex flex-col justify-start items-start">
      <h3 class="text-2xl font-semibold text-left text-gray-500 mb-2">
        John Doe
      </h3>

      <h3 class="text-lg font-semibold text-left text-gray-500 mb-4">
        Founder of Sample.com
      </h3>
    </div> 
  </div>
  <%# quote START %>
  <div class="w-full relative pt-8">
    <h3 style="font-size: 100px;position:absolute;top:-20px;left:0;" class="text-primary-purple">"
    </h3>
    <h3 class="text-lg md:text-lg text-gray-500 text-left pt-2 font-semibold">
      <span class="pl-10">This app is great!</span> 
       
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus in porro ea similique dicta unde quibusdam voluptates velit, dolore vitae reprehenderit, deserunt hic quasi consequuntur inventore facere. Ea, illum veniam.
    </h3>
  </div>
  <%# quote END %>
</div>
<%# social review card item END%>

app/views/static_pages/landing_pages/footer/_link_group1.html.erb
<%# list group items start %>
<div class="flex flex-col justify-center items-center mr-4 mb-4">
    <h1 class="text-md text-center text-gray-500 font-semibold mb-4">
    Group 1
    </h1>

    <%= link_to 'Terms of Service', termsofservice_path, class: 'text-md text-center text-gray-700 font-semibold mb-2'%>
    <%= link_to 'Privacy Policy', privacypolicy_path, class: 'text-md text-center text-gray-700 font-semibold mb-2'%>
    <%= link_to 'Link 3', root_path, class: 'text-md text-center text-gray-700 font-semibold mb-2'%>
</div>
<%# list group items end %>

app/views/static_pages/landing_pages/index.html.erb
<%= render partial: 'layouts/banners/top_banner' %>

<%# navbar START %>
<div style="-webkit-box-shadow: -2px 13px 44px -1px rgba(0,0,0,0.43);box-shadow: 0px 20px 20px 0px rgb(0 0 0 / 7%);" class="w-full py-4 bg-white flex justify-between items-center mb-4 md:mb-12">
  <%# left side start %>
  <div class="flex justify-start items-center px-4">
    <%# logo start %>
    <div class="h-6 w-6 rounded bg-gray-900 flex justify-center items-center mr-2">
      <h3 class="text-xs text-center">
        logo
      </h3>  
    </div> 
    <%# logo end %>
    <h1 class="text-3xl font-bold text-gray-900 text-left">
      MyApp
    </h1>
  </div> 
  <%# left side end %>

  <%# right side start %>
  <div class="px-4 hidden md:flex md:justify-end md:items-center ">
   <%= link_to 'Pricing', root_path, class: 'text-base text-gray-900 font-semibold mr-4'%> 
   <%= link_to 'About', root_path, class: 'text-base text-gray-900 font-semibold mr-4'%> 
   <%= link_to 'Contact', root_path, class: 'text-base text-gray-900 font-semibold mr-4'%> 
   <%= link_to 'Download', root_path, class: 'text-base text-white bg-primary-purple rounded-full py-2 px-4'%> 
  </div>
  <%# right side end %>
</div>
<%# navbar END %>

<%# hero section START %>
<div class="w-full flex flex-col justify-center items-center px-2 md:flex-row-reverse md:justify-between md:items-start md:max-w-5xl md:mx-auto mb-24">
  <div class="md:max-w-md">
    <%= image_tag 'hero-video-placeholder.png', class: 'block mb-6 mx-auto'%>
  </div>

  <div class="md:max-w-md">
    <h1 class="font-bold text-center text-4xl sm:text-5xl mb-8 md:text-left">
      This App allows you to do something cool! Read below to find out how ok?
    </h1>
    <h3 class="text-2xl text-center text-gray-500 font-semibold mb-8 md:text-left">
      Available on iOS and Android.
    </h3>
    <div class="w-full flex justify-center items-center md:justify-start">
      <%= link_to 'Download', root_path, class: 'text-xl py-4 px-10 rounded-full text-center text-white font-semibold bg-primary-purple'%>
    </div>
  </div>

</div>
<%# hero section END %>

<%# sub section 1 START %>
<div class="w-full flex flex-col justify-center items-center px-2 mb-24 md:flex-col-reverse">
  <div class="mb-12 md:max-w-md">
    <%= image_tag 'landing-subsection-video-placeholder.png', class: 'block mx-auto'%>
  </div>

  <div class="md:mb-6">
    <h1 class="text-2xl text-center font-bold text-gray-900 mb-4 md:text-4xl">
      Quick Demo
    </h1> 

    <h3 class="font-semibold text-center text-lg text-gray-500 md:text-2xl">
      Discover key features of this app in this short demo
    </h3>
  </div>
</div>
<%# sub section 1 END %>

<%# sub section 2 START %>
<div class="md:mx-auto flex flex-col justify-between items-center px-2 mb-32 md:flex-row-reverse md:max-w-5xl">
  <div class="mb-8 max-w-lg">
    <%= image_tag 'landing-subsection-2-placeholder-img.png', class: 'block mx-auto '%>
  </div>

  <div class="md:max-w-md md:mb-6">
    <h1 class="text-2xl text-center font-bold text-gray-900 mb-4 md:text-left md:text-4xl">
      Do a thing even faster than before.
    </h1> 

    <h3 class="font-semibold text-center text-lg text-gray-500 md:text-2xl md:text-left">
      No more waiting for x.y.z you can do it too!
    </h3>
  </div>
</div>
<%# sub section 2 END %>

<%# sub section 3 START %>
<div class="md:mx-auto flex flex-col justify-between items-center px-2 mb-32 md:flex-row md:max-w-5xl">
  <div class="mb-8 max-w-lg">
    <%= image_tag 'landing-subsection-3-placeholder-img.png', class: 'block mx-auto '%>
  </div>

  <div class="md:max-w-md md:mb-6">
    <h1 class="text-2xl text-center font-bold text-gray-900 mb-4 md:text-left md:text-4xl">
      Have your cake and eat it too!
    </h1> 

    <h3 class="font-semibold text-center text-lg text-gray-500 md:text-2xl md:text-left">
      using state-of-the-art cake identification
      algorithms, you can generate cake
      recipes better than your grandma 
      used to make.
    </h3>
  </div>
</div>
<%# sub section 3 END %>

<%# sub section 4 START %>
<div class="md:mx-auto flex flex-col justify-between items-center px-2 mb-32 md:flex-row-reverse md:max-w-5xl">
  <div class="mb-8 max-w-lg">
    <%= image_tag 'landing-smartwatch.png', class: 'block mx-auto '%>
  </div>

  <div class="md:max-w-md md:mb-6">
    <h1 class="text-2xl text-center font-bold text-gray-900 mb-4 md:text-left md:text-4xl">
      Integrates with your smartwatch for some reason.
    </h1> 

    <h3 class="font-semibold text-center text-lg text-gray-500 md:text-2xl md:text-left mb-4">
      Get real-time cake recipe updates to your smart watch so you never miss out on the latest trendy foody bullshit. And just what the hell does the graphic mean?
    </h3>

    <h3 class="font-semibold text-center text-lg text-gray-500 md:text-2xl md:text-left">
      <span class="text-primary-purple font-semibold">New!</span> Siri voice activated recipes, so you can get your hands dirty while keeping your phone clean.
    </h3>

  </div>
</div>
<%# sub section 4 END %>

<%# social proof START %>
<div class="w-full px-2 mb-24">
  <h1 class="text-center text-2xl font-bold text-gray-900 mb-4 md:text-4xl md:mb-8">
    Some Social Proof
   </h1>
   <%# social card items container START %>
  <div class="flex flex-col justify-center items-center md:flex-row">
    <%= render partial: 'static_pages/landing_pages/social_card' %>
    <%= render partial: 'static_pages/landing_pages/social_card' %>
    <%= render partial: 'static_pages/landing_pages/social_card' %>
  </div>
  <%# social card items container END %>
</div>
<%# social proof END %>

<%# pricing toggler START %>
<div class="md:mx-auto flex flex-col justify-between items-center px-2 mb-32 md:flex-row-reverse md:max-w-5xl">
  <div id="pricing_toggler_container" class="w-full max-w-sm">
    <%= javascript_pack_tag 'src/components/static_pages/landing_pages/PricingToggler' %>
  </div>

  <div class="md:max-w-md">
    <h1 class="text-2xl text-center font-bold text-gray-900 mb-4 md:text-left md:text-4xl">
      Easy Pricing
    </h1> 

    <h3 class="font-semibold text-center text-lg text-gray-500 md:text-2xl md:text-left mb-4">
      Get immediate access to all pro features for one low price. 
    </h3>
  </div>
</div>
<%# pricing toggler END %>

<%# exit download start %>
<div class="w-full max-w-5xl mx-auto px-4 mb-24">
  <div class="w-full flex flex-col justify-center items-center bg-gray-900 rounded-xl px-2 py-12 md:py-16 md:flex-row">
    <h1 class="text-gray-500 text-2xl text-center font-semibold mb-6 md:mb-0 md:mr-8">
      Try it for free
    </h1> 

    <div class="flex flex-row justify-center items-center">
      <%= link_to 'Download', root_path, class: 'text-xl py-4 px-16 rounded-full text-center text-white font-semibold bg-primary-purple'%>
    </div>
  </div>
</div>
<%# exit download end %>

<%# footer start %>
<div class="w-full max-w-3xl mx-auto px-4 mb-24">
 <div class="w-full flex flex-row flex-wrap justify-between items-center">
  <%# list group items start %>
  <%= render 'static_pages/landing_pages/footer/link_group1'%>
  <%= render 'static_pages/landing_pages/footer/link_group1'%>
  <%= render 'static_pages/landing_pages/footer/link_group1'%>
  <%# list group items end %>
 </div> 
</div>
<%# footer end %>

<h1 class="text-center text-gray-600">
  <%= Date.current.year %> <%= COMPANY_NAME %> 
</h1>

app/views/static_pages/privacy_policy_pages/index.html.erb
<% provide(:title, "Privacy Policy")%>
<%# top line %>
<div class="w-full py-1 bg-primary-purple"></div>

<div class="w-full py-8 px-4 flex-column items-center bg-gray-200">

  <div class="w-full max-w-4xl m-auto">
    <h1 class="font-bold text-3xl text-left text-gray-900 mb-2">Privacy Policy</h1>

    <p class="font-bold text-lg text-left mb-4 text-gray-900">Last updated: 12/20/2019</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      <%= COMPANY_NAME %> ("us", "we", or "our") operates <%= root_url %> (the
      "Site"). This page informs you of our policies regarding the collection, use and disclosure of
      Personal Information we receive from users of the Site.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      We use your Personal Information only for providing and improving the Site. By using the Site, you
agree to the collection and use of information in accordance with this policy.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      Information Collection And Use: 
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      While using our Site, we may ask you to provide us with certain personally identifiable information
that can be used to contact or identify you. Personally identifiable information may include, but is not
limited to your name ("Personal Information")
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      Log Data
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
    Like many site operators, we collect information that your browser sends whenever you visit our Site
("Log Data").
This Log Data may include information such as your computer's Internet Protocol ("IP") address,
browser type, browser version, the pages of our Site that you visit, the time and date of your visit,
the time spent on those pages and other statistics.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      Cookies:
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      Cookies are files with small amount of data, which may include an anonymous unique identifier.
Cookies are sent to your browser from a web site and stored on your computer's hard drive.
Like many sites, we use "cookies" to collect information such as your user session in order to remain logged in and access the customer dashbaord. You can instruct your browser to refuse all
cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may
not be able to use some portions of our Site.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">Security:</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      The security of your Personal Information is important to us, but remember that no method of
transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to
use commercially acceptable means to protect your Personal Information, we cannot guarantee its
absolute security.
    </p>
    
    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      Changes To This Privacy Policy:
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      This Privacy Policy is effective as of (12/20/2019) and will remain in effect except with respect to any
changes in its provisions in the future, which will be in effect immediately after being posted on this
page.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      We reserve the right to update or change our Privacy Policy at any time and you should check this
Privacy Policy periodically. Your continued use of the Service after we post any modifications to the
Privacy Policy on this page will constitute your acknowledgment of the modifications and your
consent to abide and be bound by the modified Privacy Policy.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      If we make any material changes to this Privacy Policy, we will notify you either through the email
address you have provided us, or by placing a prominent notice on our website.
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      Contact Us
    </p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">
      If you have any questions about this Privacy Policy, please contact us at support@MyApp.com
    </p>

  </div>

</div>

app/views/static_pages/tos_pages/index.html.erb
<% provide(:title, "Terms Of Service")%>

<%# top line %>
<div class="w-full py-1 bg-primary-purple"></div>

<div class="w-full py-8 px-4 flex-column items-center bg-gray-200">
  <div class="w-full max-w-4xl m-auto">
    <h1 class="font-bold text-3xl text-left text-gray-900 mb-2">Terms Of Service</h1>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">Please read these Terms and Conditions ("Terms", "Terms and Conditions" "Terms Of Service") carefully before using the <%= APP_NAME %> website and the <%= APP_NAME %> Mobile Applications (the "Service") operated by <%= COMPANY_NAME %> ("us", "we", or "our").</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">By using the <%= APP_NAME %> website and/or Mobile Applications from the ("Apple App Store or Google Play Store") you ("The Customer") enter into a contract with <%= COMPANY_NAME %> to abide by the terms of service below.</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Business Classification) - <%= APP_NAME %> is an internet business that does xyz</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Age Restrictions) - You must be 18 or older to register, sign up, access and/or create orders on the <%= APP_NAME %> website or Mobile Applications platforms. You may not use the <%= APP_NAME %> or Mobile Application for nefarious reasons purposes or for exploitive behavior.</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Website and Mobile App Availability) - There is no guarantee to you ("The Customer") that the <%= APP_NAME %> Website Or Mobile Application will be online and accessible. Site/Application Maintenance, Web Server problems or other Application related technical problems may arise and the <%= APP_NAME %> Website or Mobile Application may be offline from time to time.</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Data Loss) - <%= COMPANY_NAME %> is not responsible for any Data Loss or destruction of customer data due to unforseen technical issues related to the <%= APP_NAME %> Website or Mobile Application.</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Account Termination) - <%= COMPANY_NAME %> reserves the right to terminate A Customer (The Customer)'s' account disabling access to the <%= APP_NAME %> Website or Mobile Applications at any time for any reason.</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(3rd Party Website Links and Content) - <%= COMPANY_NAME %> is not responsible for the content or validity of any 3rd party Web Links or content that is associated with <%= APP_NAME %>, <%= APP_NAME %> Mobile Applications, or our current partners, past partners, or future partners.</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Use of the <%= APP_NAME %> Website, or Applications) - By using The <%= APP_NAME %> website and/or Mobile Applications, you warrant and certify that the information you provide to <%= COMPANY_NAME %> is accurate. <%= COMPANY_NAME %> has the right at all times to verify the validity of the information that is provided by you ("The Customer")</p>

    <p class="font-regular text-lg text-left mb-4 text-gray-900">(Refunds/Returns) - If ("The Customer") is not satisfied with the quality of service of their <%= APP_NAME %> order, they are entitled to a full refund of the order total which is available upon their request.</p>
  </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign In", new_session_path(resource_name), class: 'block text-lg text-link-blue text-center font-bold my-4' %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'block text-lg text-link-blue font-bold my-4' %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
  <% end %>
<% end %>